version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=./
      - FLASK_ENV=development
    #command: flask run --host 0.0.0.0
    command: python -m pytest -v
